name: Bug Report (FiveM)
description: File a bug report for FiveM related issues
title: "[Bug]: "
labels: ["fivem", "bug", "triage"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Please be clear and concise
      placeholder: 
    validations:
      required: true
  - type: input
    id: what-was-expected
    attributes:
      label: What did you expect would happen?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
  - type: dropdown
    id: game-version
    attributes:
      label: Game Version
      description: What version of software are you running?
      options:
	  	- 2699
	  	- 2545
        - 2189
		- N/A
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
